version: "3.8"

services:
  n8n:
    container_name: n8n
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n/backup:/backup
      - ./share:/data/shared

volumes:
  n8n_data:

